//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAS_CERTIFICATE
    {
        public string STUDENT_ID { get; set; }
        public string Certificate_ID { get; set; }
        public string DateObtained { get; set; }
        public string Issue_ID { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual Student Student { get; set; }
    }
}
