//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dojo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipPayment
    {
        public string MembershipPayment_ID { get; set; }
        public string Membership_ID { get; set; }
        public string STUDENT_ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Membership Membership { get; set; }
    }
}
